version: '3.8'

services:
  app:
    build:
      context: .
      target: development
    ports:
      - "5000:5000"
    env_file:
      - .env
    volumes:
      - ./instance:/app/instance
      - .:/app
    environment:
      - FLASK_APP=famplan.py
      - FLASK_ENV=development
      - DATABASE_URL=sqlite:///app.db
    command: >
      sh -c "flask db upgrade && flask run --host=0.0.0.0 --port=5000"

volumes:
  app-data: