services:
  app:
    build:
      context: .
      target: development
    ports:
      - "5000:5000"
    env_file:
      - .env
    volumes:
      - .:/app
    environment:
      - FLASK_APP=famplan.py
      - FLASK_ENV=development