services:
  app:
    build:
      context: .
      target: development
    ports:
      - "5000:5000"
    env_file:
      - .env
    volumes:
      - .:/app
      - ./instance:/app/instance
    working_dir: /app
    environment:
      - FLASK_APP=famplan.py
      - FLASK_ENV=development
      - PYTHONUNBUFFERED=1
    command: >
      sh -c "
      echo '=== Database Setup ===' &&
      mkdir -p /app/instance &&
      echo 'Checking migrations...' &&
      ls -la migrations/versions/ &&
      echo 'Creating initial migration...' &&
      flask db migrate -m 'Initial Docker migration' &&
      echo 'Migration created! Contents:' &&
      ls -la migrations/versions/ &&
      echo 'Running database upgrade...' &&
      flask db upgrade &&
      echo 'Database setup complete!' &&
      echo '=== Starting Flask ===' &&
      flask run --host=0.0.0.0 --port=5000
      "