"""Add family_id to Post

Revision ID: 4dba15c7bb4d
Revises: 1f90bb246085
Create Date: 2025-06-15 15:56:12.374074

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4dba15c7bb4d'
down_revision = '1f90bb246085'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.add_column(sa.Column('family_id', sa.Integer(), nullable=True))
        batch_op.create_index(batch_op.f('ix_post_family_id'), ['family_id'], unique=False)
        batch_op.create_foreign_key(None, 'family', ['family_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_post_family_id'))
        batch_op.drop_column('family_id')

    # ### end Alembic commands ###
