"""removed name(unique= true) from Family model

Revision ID: 51e45c93cdd8
Revises: 81e74fce58a4
Create Date: 2025-06-17 00:56:54.865960

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '51e45c93cdd8'
down_revision = '81e74fce58a4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('family', schema=None) as batch_op:
        batch_op.drop_constraint('family_name_key', type_='unique')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('family', schema=None) as batch_op:
        batch_op.create_unique_constraint('family_name_key', ['name'])

    # ### end Alembic commands ###
